name =  "Aalim" #This is a string(str)
age = 11 #This is an integer(int)
weight = 35.5 #This is a float(float)
student = True #This is a boolean (bool)

print("Name :", name)
print("Data Type of Name is", type(name))
print("Age :", age)
print("Data Type of Age is", type(age))
print("is_student :", student)
print("Data Type of is_student is", type(student))
print("Weight :", weight)
print("Data Type of weight is", type(weight))

print("\n After Type Casting....")
age = str(age)
print(age)
print("Data Type of age is", type(age))
weight = int(weight)
print(weight)
print("Data Type of Weight is", type(weight))